name: Cron Scrape
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Scrape
        run: |
          curl --request POST \
          --url 'https://safe-fortress-30452.herokuapp.com/' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'