name: Cron Scrape
on:
  schedule:
    - cron: '0 */72 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Scrape
        run: |
          curl --request POST \
          --url 'https://naparc-backend.onrender.com' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'